### ISSUE TITLE
This package is great, could we have it on wapm?

### ISSUE THREAD

**Issue by syrusakbary** [kateinoigakukun/irb.wasm#4]
Hi @kateinoigakukun, we are preparing the new version of WAPM and it would be great to have IRB there.

I see you already own the Ruby package, so it would be awesome if we could incorporate IRB so people can try it online like in other packages like Python: https://beta.wapm.io/python/python

**Comment by kateinoigakukun** [comment]
@syrusakbary I've published irb.wasm to WAPM

- Package: https://wapm.io/katei/irb
- Source: https://github.com/kateinoigakukun/ruby.wasm/tree/main/packages/wapm-packages/irb
